CREATE TABLE IF NOT EXISTS SEAT (
    SEAT_NUMBER VARCHAR(5) NOT NULL,
    ROOM VARCHAR(25) NOT NULL,
    CUSTOMER_NAME VARCHAR(25),
    SELL_TIME TIMESTAMP,
    CONSTRAINT ROOM_SEAT PRIMARY KEY (ROOM, SEAT_NUMBER)
);

CREATE VIEW SEAT_STATUS AS
  SELECT ROOM, SEAT_NUMBER, IIF(SELL_TIME IS NOT NULL, 'SOLD', IIF(CUSTOMER_NAME IS NOT NULL, 'RESERVED','FREE')) STATUS
  FROM SEAT;